;;; package --- Summary
;;; Commentary:
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

;;; Code:
(all-the-icons-insert-icons-for 'material)

 - 3d_rotation
 - ac_unit
 - access_alarm
 - access_alarms
 - access_time
 - accessibility
 - accessible
 - account_balance
 - account_balance_wallet
 - account_box
 - account_circle
 - adb
 - add
 - add_a_photo
 - add_alarm
 - add_alert
 - add_box
 - add_circle
 - add_circle_outline
 - add_location
 - add_shopping_cart
 - add_to_photos
 - add_to_queue
 - adjust
 - airline_seat_flat
 - airline_seat_flat_angled
 - airline_seat_individual_suite
 - airline_seat_legroom_extra
 - airline_seat_legroom_normal
 - airline_seat_legroom_reduced
 - airline_seat_recline_extra
 - airline_seat_recline_normal
 - airplanemode_active
 - airplanemode_inactive
 - airplay
 - airport_shuttle
 - alarm
 - alarm_add
 - alarm_off
 - alarm_on
 - album
 - all_inclusive
 - all_out
 - android
 - announcement
 - apps
 - archive
 - arrow_back
 - arrow_downward
 - arrow_drop_down
 - arrow_drop_down_circle
 - arrow_drop_up
 - arrow_forward
 - arrow_upward
 - art_track
 - aspect_ratio
 - assessment
 - assignment
 - assignment_ind
 - assignment_late
 - assignment_return
 - assignment_returned
 - assignment_turned_in
 - assistant
 - assistant_photo
 - attach_file
 - attach_money
 - attachment
 - audiotrack
 - autorenew
 - av_timer
 - backspace
 - backup
 - battery_alert
 - battery_charging_full
 - battery_full
 - battery_std
 - battery_unknown
 - beach_access
 - beenhere
 - block
 - bluetooth
 - bluetooth_audio
 - bluetooth_connected
 - bluetooth_disabled
 - bluetooth_searching
 - blur_circular
 - blur_linear
 - blur_off
 - blur_on
 - book
 - bookmark
 - bookmark_border
 - border_all
 - border_bottom
 - border_clear
 - border_color
 - border_horizontal
 - border_inner
 - border_left
 - border_outer
 - border_right
 - border_style
 - border_top
 - border_vertical
 - branding_watermark
 - brightness_1
 - brightness_2
 - brightness_3
 - brightness_4
 - brightness_5
 - brightness_6
 - brightness_7
 - brightness_auto
 - brightness_high
 - brightness_low
 - brightness_medium
 - broken_image
 - brush
 - bubble_chart
 - bug_report
 - build
 - burst_mode
 - business
 - business_center
 - cached
 - cake
 - call
 - call_end
 - call_made
 - call_merge
 - call_missed
 - call_missed_outgoing
 - call_received
 - call_split
 - call_to_action
 - camera
 - camera_alt
 - camera_enhance
 - camera_front
 - camera_rear
 - camera_roll
 - cancel
 - card_giftcard
 - card_membership
 - card_travel
 - casino
 - cast
 - cast_connected
 - center_focus_strong
 - center_focus_weak
 - change_history
 - chat
 - chat_bubble
 - chat_bubble_outline
 - check
 - check_box
 - check_box_outline_blank
 - check_circle
 - chevron_left
 - chevron_right
 - child_care
 - child_friendly
 - chrome_reader_mode
 - class
 - clear
 - clear_all
 - close
 - closed_caption
 - cloud
 - cloud_circle
 - cloud_done
 - cloud_download
 - cloud_off
 - cloud_queue
 - cloud_upload
 - code
 - collections
 - collections_bookmark
 - color_lens
 - colorize
 - comment
 - compare
 - compare_arrows
 - computer
 - confirmation_number
 - contact_mail
 - contact_phone
 - contacts
 - content_copy
 - content_cut
 - content_paste
 - control_point
 - control_point_duplicate
 - copyright
 - create
 - create_new_folder
 - credit_card
 - crop
 - crop_16_9
 - crop_3_2
 - crop_5_4
 - crop_7_5
 - crop_din
 - crop_free
 - crop_landscape
 - crop_original
 - crop_portrait
 - crop_rotate
 - crop_square
 - dashboard
 - data_usage
 - date_range
 - dehaze
 - delete
 - delete_forever
 - delete_sweep
 - description
 - desktop_mac
 - desktop_windows
 - details
 - developer_board
 - developer_mode
 - device_hub
 - devices
 - devices_other
 - dialer_sip
 - dialpad
 - directions
 - directions_bike
 - directions_boat
 - directions_bus
 - directions_car
 - directions_railway
 - directions_run
 - directions_subway
 - directions_transit
 - directions_walk
 - disc_full
 - dns
 - do_not_disturb
 - do_not_disturb_alt
 - do_not_disturb_off
 - do_not_disturb_on
 - dock
 - domain
 - done
 - done_all
 - donut_large
 - donut_small
 - drafts
 - drag_handle
 - drive_eta
 - dvr
 - edit
 - edit_location
 - eject
 - email
 - enhanced_encryption
 - equalizer
 - error
 - error_outline
 - euro_symbol
 - ev_station
 - event
 - event_available
 - event_busy
 - event_note
 - event_seat
 - exit_to_app
 - expand_less
 - expand_more
 - explicit
 - explore
 - exposure
 - exposure_neg_1
 - exposure_neg_2
 - exposure_plus_1
 - exposure_plus_2
 - exposure_zero
 - extension
 - face
 - fast_forward
 - fast_rewind
 - favorite
 - favorite_border
 - featured_play_list
 - featured_video
 - feedback
 - fiber_dvr
 - fiber_manual_record
 - fiber_new
 - fiber_pin
 - fiber_smart_record
 - file_download
 - file_upload
 - filter
 - filter_1
 - filter_2
 - filter_3
 - filter_4
 - filter_5
 - filter_6
 - filter_7
 - filter_8
 - filter_9
 - filter_9_plus
 - filter_b_and_w
 - filter_center_focus
 - filter_drama
 - filter_frames
 - filter_hdr
 - filter_list
 - filter_none
 - filter_tilt_shift
 - filter_vintage
 - find_in_page
 - find_replace
 - fingerprint
 - first_page
 - fitness_center
 - flag
 - flare
 - flash_auto
 - flash_off
 - flash_on
 - flight
 - flight_land
 - flight_takeoff
 - flip
 - flip_to_back
 - flip_to_front
 - folder
 - folder_open
 - folder_shared
 - folder_special
 - font_download
 - format_align_center
 - format_align_justify
 - format_align_left
 - format_align_right
 - format_bold
 - format_clear
 - format_color_fill
 - format_color_reset
 - format_color_text
 - format_indent_decrease
 - format_indent_increase
 - format_italic
 - format_line_spacing
 - format_list_bulleted
 - format_list_numbered
 - format_paint
 - format_quote
 - format_shapes
 - format_size
 - format_strikethrough
 - format_textdirection_l_to_r
 - format_textdirection_r_to_l
 - format_underlined
 - forum
 - forward
 - forward_10
 - forward_30
 - forward_5
 - free_breakfast
 - fullscreen
 - fullscreen_exit
 - functions
 - g_translate
 - gamepad
 - games
 - gavel
 - gesture
 - get_app
 - gif
 - golf_course
 - gps_fixed
 - gps_not_fixed
 - gps_off
 - grade
 - gradient
 - grain
 - graphic_eq
 - grid_off
 - grid_on
 - group
 - group_add
 - group_work
 - hd
 - hdr_off
 - hdr_on
 - hdr_strong
 - hdr_weak
 - headset
 - headset_mic
 - healing
 - hearing
 - help
 - help_outline
 - high_quality
 - highlight
 - highlight_off
 - history
 - home
 - hot_tub
 - hotel
 - hourglass_empty
 - hourglass_full
 - http
 - https
 - image
 - image_aspect_ratio
 - import_contacts
 - import_export
 - important_devices
 - inbox
 - indeterminate_check_box
 - info
 - info_outline
 - input
 - insert_chart
 - insert_comment
 - insert_drive_file
 - insert_emoticon
 - insert_invitation
 - insert_link
 - insert_photo
 - invert_colors
 - invert_colors_off
 - iso
 - keyboard
 - keyboard_arrow_down
 - keyboard_arrow_left
 - keyboard_arrow_right
 - keyboard_arrow_up
 - keyboard_backspace
 - keyboard_capslock
 - keyboard_hide
 - keyboard_return
 - keyboard_tab
 - keyboard_voice
 - kitchen
 - label
 - label_outline
 - landscape
 - language
 - laptop
 - laptop_chromebook
 - laptop_mac
 - laptop_windows
 - last_page
 - launch
 - layers
 - layers_clear
 - leak_add
 - leak_remove
 - lens
 - library_add
 - library_books
 - library_music
 - lightbulb_outline
 - line_style
 - line_weight
 - linear_scale
 - link
 - linked_camera
 - list
 - live_help
 - live_tv
 - local_activity
 - local_airport
 - local_atm
 - local_bar
 - local_cafe
 - local_car_wash
 - local_convenience_store
 - local_dining
 - local_drink
 - local_florist
 - local_gas_station
 - local_grocery_store
 - local_hospital
 - local_hotel
 - local_laundry_service
 - local_library
 - local_mall
 - local_movies
 - local_offer
 - local_parking
 - local_pharmacy
 - local_phone
 - local_pizza
 - local_play
 - local_post_office
 - local_printshop
 - local_see
 - local_shipping
 - local_taxi
 - location_city
 - location_disabled
 - location_off
 - location_on
 - location_searching
 - lock
 - lock_open
 - lock_outline
 - looks
 - looks_3
 - looks_4
 - looks_5
 - looks_6
 - looks_one
 - looks_two
 - loop
 - loupe
 - low_priority
 - loyalty
 - mail
 - mail_outline
 - map
 - markunread
 - markunread_mailbox
 - memory
 - menu
 - merge_type
 - message
 - mic
 - mic_none
 - mic_off
 - mms
 - mode_comment
 - mode_edit
 - monetization_on
 - money_off
 - monochrome_photos
 - mood
 - mood_bad
 - more
 - more_horiz
 - more_vert
 - motorcycle
 - mouse
 - move_to_inbox
 - movie
 - movie_creation
 - movie_filter
 - multiline_chart
 - music_note
 - music_video
 - my_location
 - nature
 - nature_people
 - navigate_before
 - navigate_next
 - navigation
 - near_me
 - network_cell
 - network_check
 - network_locked
 - network_wifi
 - new_releases
 - next_week
 - nfc
 - no_encryption
 - no_sim
 - not_interested
 - note
 - note_add
 - notifications
 - notifications_active
 - notifications_none
 - notifications_off
 - notifications_paused
 - offline_pin
 - ondemand_video
 - opacity
 - open_in_browser
 - open_in_new
 - open_with
 - pages
 - pageview
 - palette
 - pan_tool
 - panorama
 - panorama_fish_eye
 - panorama_horizontal
 - panorama_vertical
 - panorama_wide_angle
 - party_mode
 - pause
 - pause_circle_filled
 - pause_circle_outline
 - payment
 - people
 - people_outline
 - perm_camera_mic
 - perm_contact_calendar
 - perm_data_setting
 - perm_device_information
 - perm_identity
 - perm_media
 - perm_phone_msg
 - perm_scan_wifi
 - person
 - person_add
 - person_outline
 - person_pin
 - person_pin_circle
 - personal_video
 - pets
 - phone
 - phone_android
 - phone_bluetooth_speaker
 - phone_forwarded
 - phone_in_talk
 - phone_iphone
 - phone_locked
 - phone_missed
 - phone_paused
 - phonelink
 - phonelink_erase
 - phonelink_lock
 - phonelink_off
 - phonelink_ring
 - phonelink_setup
 - photo
 - photo_album
 - photo_camera
 - photo_filter
 - photo_library
 - photo_size_select_actual
 - photo_size_select_large
 - photo_size_select_small
 - picture_as_pdf
 - picture_in_picture
 - picture_in_picture_alt
 - pie_chart
 - pie_chart_outlined
 - pin_drop
 - place
 - play_arrow
 - play_circle_filled
 - play_circle_outline
 - play_for_work
 - playlist_add
 - playlist_add_check
 - playlist_play
 - plus_one
 - poll
 - polymer
 - pool
 - portable_wifi_off
 - portrait
 - power
 - power_input
 - power_settings_new
 - pregnant_woman
 - present_to_all
 - print
 - priority_high
 - public
 - publish
 - query_builder
 - question_answer
 - queue
 - queue_music
 - queue_play_next
 - radio
 - radio_button_checked
 - radio_button_unchecked
 - rate_review
 - receipt
 - recent_actors
 - record_voice_over
 - redeem
 - redo
 - refresh
 - remove
 - remove_circle
 - remove_circle_outline
 - remove_from_queue
 - remove_red_eye
 - remove_shopping_cart
 - reorder
 - repeat
 - repeat_one
 - replay
 - replay_10
 - replay_30
 - replay_5
 - reply
 - reply_all
 - report
 - report_problem
 - restaurant
 - restaurant_menu
 - restore
 - restore_page
 - ring_volume
 - room
 - room_service
 - rotate_90_degrees_ccw
 - rotate_left
 - rotate_right
 - rounded_corner
 - router
 - rowing
 - rss_feed
 - rv_hookup
 - satellite
 - save
 - scanner
 - schedule
 - school
 - screen_lock_landscape
 - screen_lock_portrait
 - screen_lock_rotation
 - screen_rotation
 - screen_share
 - sd_card
 - sd_storage
 - search
 - security
 - select_all
 - send
 - sentiment_dissatisfied
 - sentiment_neutral
 - sentiment_satisfied
 - sentiment_very_dissatisfied
 - sentiment_very_satisfied
 - settings
 - settings_applications
 - settings_backup_restore
 - settings_bluetooth
 - settings_brightness
 - settings_cell
 - settings_ethernet
 - settings_input_antenna
 - settings_input_component
 - settings_input_composite
 - settings_input_hdmi
 - settings_input_svideo
 - settings_overscan
 - settings_phone
 - settings_power
 - settings_remote
 - settings_system_daydream
 - settings_voice
 - share
 - shop
 - shop_two
 - shopping_basket
 - shopping_cart
 - short_text
 - show_chart
 - shuffle
 - signal_cellular_4_bar
 - signal_cellular_connected_no_internet_4_bar
 - signal_cellular_no_sim
 - signal_cellular_null
 - signal_cellular_off
 - signal_wifi_4_bar
 - signal_wifi_4_bar_lock
 - signal_wifi_off
 - sim_card
 - sim_card_alert
 - skip_next
 - skip_previous
 - slideshow
 - slow_motion_video
 - smartphone
 - smoke_free
 - smoking_rooms
 - sms
 - sms_failed
 - snooze
 - sort
 - sort_by_alpha
 - spa
 - space_bar
 - speaker
 - speaker_group
 - speaker_notes
 - speaker_notes_off
 - speaker_phone
 - spellcheck
 - star
 - star_border
 - star_half
 - stars
 - stay_current_landscape
 - stay_current_portrait
 - stay_primary_landscape
 - stay_primary_portrait
 - stop
 - stop_screen_share
 - storage
 - store
 - store_mall_directory
 - straighten
 - streetview
 - strikethrough_s
 - style
 - subdirectory_arrow_left
 - subdirectory_arrow_right
 - subject
 - subscriptions
 - subtitles
 - subway
 - supervisor_account
 - surround_sound
 - swap_calls
 - swap_horiz
 - swap_vert
 - swap_vertical_circle
 - switch_camera
 - switch_video
 - sync
 - sync_disabled
 - sync_problem
 - system_update
 - system_update_alt
 - tab
 - tab_unselected
 - tablet
 - tablet_android
 - tablet_mac
 - tag_faces
 - tap_and_play
 - terrain
 - text_fields
 - text_format
 - textsms
 - texture
 - theaters
 - thumb_down
 - thumb_up
 - thumbs_up_down
 - time_to_leave
 - timelapse
 - timeline
 - timer
 - timer_10
 - timer_3
 - timer_off
 - title
 - toc
 - today
 - toll
 - tonality
 - touch_app
 - toys
 - track_changes
 - traffic
 - train
 - tram
 - transfer_within_a_station
 - transform
 - translate
 - trending_down
 - trending_flat
 - trending_up
 - tune
 - turned_in
 - turned_in_not
 - tv
 - unarchive
 - undo
 - unfold_less
 - unfold_more
 - update
 - usb
 - verified_user
 - vertical_align_bottom
 - vertical_align_center
 - vertical_align_top
 - vibration
 - video_call
 - video_label
 - video_library
 - videocam
 - videocam_off
 - videogame_asset
 - view_agenda
 - view_array
 - view_carousel
 - view_column
 - view_comfy
 - view_compact
 - view_day
 - view_headline
 - view_list
 - view_module
 - view_quilt
 - view_stream
 - view_week
 - vignette
 - visibility
 - visibility_off
 - voice_chat
 - voicemail
 - volume_down
 - volume_mute
 - volume_off
 - volume_up
 - vpn_key
 - vpn_lock
 - wallpaper
 - warning
 - watch
 - watch_later
 - wb_auto
 - wb_cloudy
 - wb_incandescent
 - wb_iridescent
 - wb_sunny
 - wc
 - web
 - web_asset
 - weekend
 - whatshot
 - widgets
 - wifi
 - wifi_lock
 - wifi_tethering
 - work
 - wrap_text
 - youtube_searched_for
 - zoom_in
 - zoom_out
 - zoom_out_map

(all-the-icons-insert-icons-for 'alltheicon)
 - apache
 - atom
 - aws
 - bower
 - c
 - c-line
 - clojure
 - clojure-line
 - coffeescript
 - cplusplus
 - cplusplus-line
 - csharp
 - csharp-line
 - css3
 - css3-alt
 - d3
 - dlang
 - elixir
 - erlang
 - git
 - go
 - google-drive
 - grunt
 - grunt-line
 - gulp
 - haskell
 - html5
 - jasmine
 - java
 - javascript
 - javascript-badge
 - javascript-shield
 - less
 - nginx
 - nodejs
 - perl
 - perldocs
 - postgresql
 - prolog
 - python
 - react
 - ruby
 - ruby-alt
 - rust
 - sass
 - scala
 - script
 - spring
 - stylus
 - svg
 - swift
 - terminal
 - terminal-alt
 - battery-charging
 - arrow-left
 - arrow-right
 - cup-left
 - cup-right
 - slant-left
 - slant-right
 - wave-left
 - wave-right

(all-the-icons-insert-icons-for 'octicon)
 - alert
 - arrow-down
 - arrow-left
 - arrow-right
 - arrow-small-down
 - arrow-small-left
 - arrow-small-right
 - arrow-small-up
 - arrow-up
 - book
 - bookmark
 - briefcase
 - broadcast
 - browser
 - bug
 - calendar
 - check
 - checklist
 - chevron-down
 - chevron-left
 - chevron-right
 - chevron-up
 - circle-slash
 - circuit-board
 - clippy
 - clock
 - cloud-download
 - cloud-upload
 - code
 - comment
 - comment-discussion
 - credit-card
 - dash
 - dashboard
 - database
 - device-camera
 - device-camera-video
 - device-desktop
 - device-mobile
 - diff
 - diff-added
 - diff-ignored
 - diff-modified
 - diff-removed
 - diff-renamed
 - ellipsis
 - eye
 - file-binary
 - file-code
 - file-directory
 - file-media
 - file-pdf
 - file-submodule
 - file-symlink-directory
 - file-symlink-file
 - file-text
 - file-zip
 - flame
 - fold
 - gear
 - gift
 - gist
 - gist-secret
 - git-branch
 - git-commit
 - git-compare
 - git-merge
 - git-pull-request
 - globe
 - graph
 - beaker
♥ - heart
 - history
 - home
 - horizontal-rule
 - hourglass
 - hubot
 - inbox
 - info
 - issue-closed
 - issue-opened
 - issue-reopened
 - jersey
 - key
 - keyboard
 - law
 - light-bulb
 - link
 - link-external
 - list-ordered
 - list-unordered
 - location
 - lock
 - logo-github
 - mail
 - mail-read
 - mail-reply
 - mark-github
 - markdown
 - megaphone
 - mention
 - milestone
 - mirror
 - mortar-board
 - mute
 - no-newline
 - octoface
 - organization
 - package
 - paintcan
 - pencil
 - person
 - pin
 - plug
 - plus
 - primitive-dot
 - primitive-square
 - pulse
 - puzzle
 - question
 - quote
 - radio-tower
 - repo
 - repo-clone
 - repo-force-push
 - repo-forked
 - repo-pull
 - repo-push
 - rocket
 - rss
 - ruby
 - search
 - server
 - settings
 - sign-in
 - sign-out
 - squirrel
 - star
 - steps
 - stop
 - sync
 - tag
 - telescope
 - terminal
 - three-bars
 - thumbsdown
 - thumbsup
 - tools
 - trashcan
 - triangle-down
 - triangle-left
 - triangle-right
 - triangle-up
 - unfold
 - unmute
 - versions
 - x
⚡ - zap

(all-the-icons-insert-icons-for 'wicon)
 - alien
 - barometer
 - celsius
 - cloud
 - cloud-down
 - cloud-refresh
 - cloud-up
 - cloudy
 - cloudy-gusts
 - cloudy-windy
 - day-cloudy
 - day-cloudy-gusts
 - day-cloudy-high
 - day-cloudy-windy
 - day-fog
 - day-hail
 - day-haze
 - day-light-wind
 - day-lightning
 - day-rain
 - day-rain-mix
 - day-rain-wind
 - day-showers
 - day-sleet
 - day-sleet-storm
 - day-snow
 - day-snow-thunderstorm
 - day-snow-wind
 - day-sprinkle
 - day-storm-showers
 - day-sunny
 - day-sunny-overcast
 - day-thunderstorm
 - day-windy
 - degrees
 - direction-down
 - direction-down-left
 - direction-down-right
 - direction-left
 - direction-right
 - direction-up
 - direction-up-left
 - direction-up-right
 - dust
 - earthquake
 - fahrenheit
 - fire
 - flood
 - fog
 - forecast-io-clear-day
 - forecast-io-clear-night
 - forecast-io-cloudy
 - forecast-io-fog
 - forecast-io-hail
 - forecast-io-partly-cloudy-day
 - forecast-io-partly-cloudy-night
 - forecast-io-rain
 - forecast-io-sleet
 - forecast-io-snow
 - forecast-io-thunderstorm
 - forecast-io-tornado
 - forecast-io-wind
 - gale-warning
 - hail
 - horizon
 - horizon-alt
 - hot
 - humidity
 - hurricane
 - hurricane-warning
 - lightning
 - lunar-eclipse
 - meteor
 - moon-0
 - moon-1
 - moon-10
 - moon-11
 - moon-12
 - moon-13
 - moon-14
 - moon-15
 - moon-16
 - moon-17
 - moon-18
 - moon-19
 - moon-2
 - moon-20
 - moon-21
 - moon-22
 - moon-23
 - moon-24
 - moon-25
 - moon-26
 - moon-27
 - moon-3
 - moon-4
 - moon-5
 - moon-6
 - moon-7
 - moon-8
 - moon-9
 - moon-alt-first-quarter
 - moon-alt-full
 - moon-alt-new
 - moon-alt-third-quarter
 - moon-alt-waning-crescent-1
 - moon-alt-waning-crescent-2
 - moon-alt-waning-crescent-3
 - moon-alt-waning-crescent-4
 - moon-alt-waning-crescent-5
 - moon-alt-waning-crescent-6
 - moon-alt-waning-gibbous-1
 - moon-alt-waning-gibbous-2
 - moon-alt-waning-gibbous-3
 - moon-alt-waning-gibbous-4
 - moon-alt-waning-gibbous-5
 - moon-alt-waning-gibbous-6
 - moon-alt-waxing-crescent-1
 - moon-alt-waxing-crescent-2
 - moon-alt-waxing-crescent-3
 - moon-alt-waxing-crescent-4
 - moon-alt-waxing-crescent-5
 - moon-alt-waxing-crescent-6
 - moon-alt-waxing-gibbous-1
 - moon-alt-waxing-gibbous-2
 - moon-alt-waxing-gibbous-3
 - moon-alt-waxing-gibbous-4
 - moon-alt-waxing-gibbous-5
 - moon-alt-waxing-gibbous-6
 - moon-first-quarter
 - moon-full
 - moon-new
 - moon-third-quarter
 - moon-waning-crescent-1
 - moon-waning-crescent-2
 - moon-waning-crescent-3
 - moon-waning-crescent-4
 - moon-waning-crescent-5
 - moon-waning-crescent-6
 - moon-waning-gibbous-1
 - moon-waning-gibbous-2
 - moon-waning-gibbous-3
 - moon-waning-gibbous-4
 - moon-waning-gibbous-5
 - moon-waning-gibbous-6
 - moon-waxing-crescent-1
 - moon-waxing-crescent-2
 - moon-waxing-crescent-3
 - moon-waxing-crescent-4
 - moon-waxing-crescent-5
 - moon-waxing-crescent-6
 - moon-waxing-gibbous-1
 - moon-waxing-gibbous-2
 - moon-waxing-gibbous-3
 - moon-waxing-gibbous-4
 - moon-waxing-gibbous-5
 - moon-waxing-gibbous-6
 - moonrise
 - moonset
 - na
 - night-alt-cloudy
 - night-alt-cloudy-gusts
 - night-alt-cloudy-high
 - night-alt-cloudy-windy
 - night-alt-hail
 - night-alt-lightning
 - night-alt-partly-cloudy
 - night-alt-rain
 - night-alt-rain-mix
 - night-alt-rain-wind
 - night-alt-showers
 - night-alt-sleet
 - night-alt-sleet-storm
 - night-alt-snow
 - night-alt-snow-thunderstorm
 - night-alt-snow-wind
 - night-alt-sprinkle
 - night-alt-storm-showers
 - night-alt-thunderstorm
 - night-clear
 - night-cloudy
 - night-cloudy-gusts
 - night-cloudy-high
 - night-cloudy-windy
 - night-fog
 - night-hail
 - night-lightning
 - night-partly-cloudy
 - night-rain
 - night-rain-mix
 - night-rain-wind
 - night-showers
 - night-sleet
 - night-sleet-storm
 - night-snow
 - night-snow-thunderstorm
 - night-snow-wind
 - night-sprinkle
 - night-storm-showers
 - night-thunderstorm
 - owm-200
 - owm-201
 - owm-202
 - owm-210
 - owm-211
 - owm-212
 - owm-221
 - owm-230
 - owm-231
 - owm-232
 - owm-300
 - owm-301
 - owm-302
 - owm-310
 - owm-311
 - owm-312
 - owm-313
 - owm-314
 - owm-321
 - owm-500
 - owm-501
 - owm-502
 - owm-503
 - owm-504
 - owm-511
 - owm-520
 - owm-521
 - owm-522
 - owm-531
 - owm-600
 - owm-601
 - owm-602
 - owm-611
 - owm-612
 - owm-615
 - owm-616
 - owm-620
 - owm-621
 - owm-622
 - owm-701
 - owm-711
 - owm-721
 - owm-731
 - owm-741
 - owm-761
 - owm-762
 - owm-771
 - owm-781
 - owm-800
 - owm-801
 - owm-802
 - owm-803
 - owm-804
 - owm-900
 - owm-901
 - owm-902
 - owm-903
 - owm-904
 - owm-905
 - owm-906
 - owm-957
 - owm-day-200
 - owm-day-201
 - owm-day-202
 - owm-day-210
 - owm-day-211
 - owm-day-212
 - owm-day-221
 - owm-day-230
 - owm-day-231
 - owm-day-232
 - owm-day-300
 - owm-day-301
 - owm-day-302
 - owm-day-310
 - owm-day-311
 - owm-day-312
 - owm-day-313
 - owm-day-314
 - owm-day-321
 - owm-day-500
 - owm-day-501
 - owm-day-502
 - owm-day-503
 - owm-day-504
 - owm-day-511
 - owm-day-520
 - owm-day-521
 - owm-day-522
 - owm-day-531
 - owm-day-600
 - owm-day-601
 - owm-day-602
 - owm-day-611
 - owm-day-612
 - owm-day-615
 - owm-day-616
 - owm-day-620
 - owm-day-621
 - owm-day-622
 - owm-day-701
 - owm-day-711
 - owm-day-721
 - owm-day-731
 - owm-day-741
 - owm-day-761
 - owm-day-762
 - owm-day-781
 - owm-day-800
 - owm-day-801
 - owm-day-802
 - owm-day-803
 - owm-day-804
 - owm-day-900
 - owm-day-902
 - owm-day-903
 - owm-day-904
 - owm-day-906
 - owm-day-957
 - owm-night-200
 - owm-night-201
 - owm-night-202
 - owm-night-210
 - owm-night-211
 - owm-night-212
 - owm-night-221
 - owm-night-230
 - owm-night-231
 - owm-night-232
 - owm-night-300
 - owm-night-301
 - owm-night-302
 - owm-night-310
 - owm-night-311
 - owm-night-312
 - owm-night-313
 - owm-night-314
 - owm-night-321
 - owm-night-500
 - owm-night-501
 - owm-night-502
 - owm-night-503
 - owm-night-504
 - owm-night-511
 - owm-night-520
 - owm-night-521
 - owm-night-522
 - owm-night-531
 - owm-night-600
 - owm-night-601
 - owm-night-602
 - owm-night-611
 - owm-night-612
 - owm-night-615
 - owm-night-616
 - owm-night-620
 - owm-night-621
 - owm-night-622
 - owm-night-701
 - owm-night-711
 - owm-night-721
 - owm-night-731
 - owm-night-741
 - owm-night-761
 - owm-night-762
 - owm-night-781
 - owm-night-800
 - owm-night-801
 - owm-night-802
 - owm-night-803
 - owm-night-804
 - owm-night-900
 - owm-night-902
 - owm-night-903
 - owm-night-904
 - owm-night-906
 - owm-night-957
 - rain
 - rain-mix
 - rain-wind
 - raindrop
 - raindrops
 - refresh
 - refresh-alt
 - sandstorm
 - showers
 - sleet
 - small-craft-advisory
 - smog
 - smoke
 - snow
 - snow
 - snow-wind
 - snowflake-cold
 - solar-eclipse
 - sprinkle
 - stars
 - storm-showers
 - storm-showers
 - storm-warning
 - strong-wind
 - sunrise
 - sunset
 - thermometer
 - thermometer-exterior
 - thermometer-internal
 - thunderstorm
 - thunderstorm
 - time-1
 - time-10
 - time-11
 - time-12
 - time-2
 - time-3
 - time-4
 - time-5
 - time-6
 - time-7
 - time-8
 - time-9
 - tornado
 - train
 - tsunami
 - umbrella
 - volcano
 - wind-beaufort-0
 - wind-beaufort-1
 - wind-beaufort-10
 - wind-beaufort-11
 - wind-beaufort-12
 - wind-beaufort-2
 - wind-beaufort-3
 - wind-beaufort-4
 - wind-beaufort-5
 - wind-beaufort-6
 - wind-beaufort-7
 - wind-beaufort-8
 - wind-beaufort-9
 - wind-direction
 - windy
 - wmo4680-00
 - wmo4680-01
 - wmo4680-02
 - wmo4680-03
 - wmo4680-04
 - wmo4680-05
 - wmo4680-10
 - wmo4680-11
 - wmo4680-12
 - wmo4680-18
 - wmo4680-20
 - wmo4680-21
 - wmo4680-22
 - wmo4680-23
 - wmo4680-24
 - wmo4680-25
 - wmo4680-26
 - wmo4680-27
 - wmo4680-28
 - wmo4680-29
 - wmo4680-30
 - wmo4680-31
 - wmo4680-32
 - wmo4680-33
 - wmo4680-34
 - wmo4680-35
 - wmo4680-40
 - wmo4680-41
 - wmo4680-42
 - wmo4680-43
 - wmo4680-44
 - wmo4680-45
 - wmo4680-46
 - wmo4680-47
 - wmo4680-48
 - wmo4680-50
 - wmo4680-51
 - wmo4680-52
 - wmo4680-53
 - wmo4680-54
 - wmo4680-55
 - wmo4680-56
 - wmo4680-57
 - wmo4680-58
 - wmo4680-60
 - wmo4680-61
 - wmo4680-62
 - wmo4680-63
 - wmo4680-64
 - wmo4680-65
 - wmo4680-66
 - wmo4680-67
 - wmo4680-68
 - wmo4680-70
 - wmo4680-71
 - wmo4680-72
 - wmo4680-73
 - wmo4680-74
 - wmo4680-75
 - wmo4680-76
 - wmo4680-77
 - wmo4680-78
 - wmo4680-80
 - wmo4680-81
 - wmo4680-82
 - wmo4680-83
 - wmo4680-84
 - wmo4680-85
 - wmo4680-86
 - wmo4680-87
 - wmo4680-89
 - wmo4680-90
 - wmo4680-91
 - wmo4680-92
 - wmo4680-93
 - wmo4680-94
 - wmo4680-95
 - wmo4680-96
 - wmo4680-99
 - wu-chanceflurries
 - wu-chancerain
 - wu-chancesleat
 - wu-chancesnow
 - wu-chancetstorms
 - wu-clear
 - wu-cloudy
 - wu-flurries
 - wu-hazy
 - wu-mostlycloudy
 - wu-mostlysunny
 - wu-partlycloudy
 - wu-partlysunny
 - wu-rain
 - wu-sleat
 - wu-snow
 - wu-sunny
 - wu-tstorms
 - wu-unknown
 - yahoo-0
 - yahoo-1
 - yahoo-10
 - yahoo-11
 - yahoo-12
 - yahoo-13
 - yahoo-14
 - yahoo-15
 - yahoo-16
 - yahoo-17
 - yahoo-18
 - yahoo-19
 - yahoo-2
 - yahoo-20
 - yahoo-21
 - yahoo-22
 - yahoo-23
 - yahoo-24
 - yahoo-25
 - yahoo-26
 - yahoo-27
 - yahoo-28
 - yahoo-29
 - yahoo-3
 - yahoo-30
 - yahoo-31
 - yahoo-32
 - yahoo-3200
 - yahoo-33
 - yahoo-34
 - yahoo-35
 - yahoo-36
 - yahoo-37
 - yahoo-38
 - yahoo-39
 - yahoo-4
 - yahoo-40
 - yahoo-41
 - yahoo-42
 - yahoo-43
 - yahoo-44
 - yahoo-45
 - yahoo-46
 - yahoo-47
 - yahoo-5
 - yahoo-6
 - yahoo-7
 - yahoo-8
 - yahoo-9

(all-the-icons-insert-icons-for 'faicon)
 - 500px
 - adjust
 - adn
 - align-center
 - align-justify
 - align-left
 - align-right
 - amazon
 - ambulance
 - american-sign-language-interpreting
 - anchor
 - android
 - angellist
 - angle-double-down
 - angle-double-left
 - angle-double-right
 - angle-double-up
 - angle-down
 - angle-left
 - angle-right
 - angle-up
 - apple
 - archive
 - area-chart
 - arrow-circle-down
 - arrow-circle-left
 - arrow-circle-o-down
 - arrow-circle-o-left
 - arrow-circle-o-right
 - arrow-circle-o-up
 - arrow-circle-right
 - arrow-circle-up
 - arrow-down
 - arrow-left
 - arrow-right
 - arrow-up
 - arrows
 - arrows-alt
 - arrows-h
 - arrows-v
 - assistive-listening-systems
 - asterisk
 - at
 - audio-description
 - backward
 - balance-scale
 - ban
 - bar-chart
 - barcode
 - bars
 - battery-empty
 - battery-full
 - battery-half
 - battery-quarter
 - battery-three-quarters
 - bed
 - beer
 - behance
 - behance-square
 - bell
 - bell-o
 - bell-slash
 - bell-slash-o
 - bicycle
 - binoculars
 - birthday-cake
 - bitbucket
 - bitbucket-square
 - black-tie
 - blind
 - bluetooth
 - bluetooth-b
 - bold
 - bolt
 - bomb
 - book
 - bookmark
 - bookmark-o
 - braille
 - briefcase
 - btc
 - bug
 - building
 - building-o
 - bullhorn
 - bullseye
 - bus
 - buysellads
 - calculator
 - calendar
 - calendar-check-o
 - calendar-minus-o
 - calendar-o
 - calendar-plus-o
 - calendar-times-o
 - camera
 - camera-retro
 - car
 - caret-down
 - caret-left
 - caret-right
 - caret-square-o-down
 - caret-square-o-left
 - caret-square-o-right
 - caret-square-o-up
 - caret-up
 - cart-arrow-down
 - cart-plus
 - cc
 - cc-amex
 - cc-diners-club
 - cc-discover
 - cc-jcb
 - cc-mastercard
 - cc-paypal
 - cc-stripe
 - cc-visa
 - certificate
 - chain-broken
 - check
 - check-circle
 - check-circle-o
 - check-square
 - check-square-o
 - chevron-circle-down
 - chevron-circle-left
 - chevron-circle-right
 - chevron-circle-up
 - chevron-down
 - chevron-left
 - chevron-right
 - chevron-up
 - child
 - chrome
 - circle
 - circle-o
 - circle-o-notch
 - circle-thin
 - clipboard
 - clock-o
 - clone
 - cloud
 - cloud-download
 - cloud-upload
 - code
 - code-fork
 - codepen
 - codiepie
 - coffee
 - cog
 - cogs
 - columns
 - comment
 - comment-o
 - commenting
 - commenting-o
 - comments
 - comments-o
 - compass
 - compress
 - connectdevelop
 - contao
 - copyright
 - creative-commons
 - credit-card
 - credit-card-alt
 - crop
 - crosshairs
 - css3
 - cube
 - cubes
 - cutlery
 - dashcube
 - database
 - deaf
 - delicious
 - desktop
 - deviantart
 - diamond
 - digg
 - dot-circle-o
 - download
 - dribbble
 - dropbox
 - drupal
 - edge
 - eject
 - ellipsis-h
 - ellipsis-v
 - empire
 - envelope
 - envelope-o
 - envelope-square
 - envira
 - eraser
 - eur
 - exchange
 - exclamation
 - exclamation-circle
 - exclamation-triangle
 - expand
 - expeditedssl
 - external-link
 - external-link-square
 - eye
 - eye-slash
 - eyedropper
 - facebook
 - facebook-official
 - facebook-square
 - fast-backward
 - fast-forward
 - fax
 - female
 - fighter-jet
 - file
 - file-archive-o
 - file-audio-o
 - file-code-o
 - file-excel-o
 - file-image-o
 - file-o
 - file-pdf-o
 - file-powerpoint-o
 - file-text
 - file-text-o
 - file-video-o
 - file-word-o
 - files-o
 - film
 - filter
 - fire
 - fire-extinguisher
 - firefox
 - first-order
 - flag
 - flag-checkered
 - flag-o
 - flask
 - flickr
 - floppy-o
 - folder
 - folder-o
 - folder-open
 - folder-open-o
 - font
 - font-awesome
 - fonticons
 - fort-awesome
 - forumbee
 - forward
 - foursquare
 - frown-o
 - futbol-o
 - gamepad
 - gavel
 - gbp
 - genderless
 - get-pocket
 - gg
 - gg-circle
 - gift
 - git
 - git-square
 - github
 - github-alt
 - github-square
 - gitlab
 - glass
 - glide
 - glide-g
 - globe
 - google
 - google-plus
 - google-plus-official
 - google-plus-square
 - google-wallet
 - graduation-cap
 - gratipay
 - h-square
 - hacker-news
 - hand-lizard-o
 - hand-o-down
 - hand-o-left
 - hand-o-right
 - hand-o-up
 - hand-paper-o
 - hand-peace-o
 - hand-pointer-o
 - hand-rock-o
 - hand-scissors-o
 - hand-spock-o
 - hashtag
 - hdd-o
 - header
 - headphones
 - heart
 - heart-o
 - heartbeat
 - history
 - home
 - hospital-o
 - hourglass
 - hourglass-end
 - hourglass-half
 - hourglass-o
 - hourglass-start
 - houzz
 - html5
 - i-cursor
 - ils
 - inbox
 - indent
 - industry
 - info
 - info-circle
 - inr
 - instagram
 - internet-explorer
 - ioxhost
 - italic
 - joomla
 - jpy
 - jsfiddle
 - key
 - keyboard-o
 - krw
 - language
 - laptop
 - lastfm
 - lastfm-square
 - leaf
 - leanpub
 - lemon-o
 - level-down
 - level-up
 - life-ring
 - lightbulb-o
 - line-chart
 - link
 - linkedin
 - linkedin-square
 - linux
 - list
 - list-alt
 - list-ol
 - list-ul
 - location-arrow
 - lock
 - long-arrow-down
 - long-arrow-left
 - long-arrow-right
 - long-arrow-up
 - low-vision
 - magic
 - magnet
 - male
 - map
 - map-marker
 - map-o
 - map-pin
 - map-signs
 - mars
 - mars-double
 - mars-stroke
 - mars-stroke-h
 - mars-stroke-v
 - maxcdn
 - meanpath
 - medium
 - medkit
 - meh-o
 - mercury
 - microphone
 - microphone-slash
 - minus
 - minus-circle
 - minus-square
 - minus-square-o
 - mixcloud
 - mobile
 - modx
 - money
 - moon-o
 - motorcycle
 - mouse-pointer
 - music
 - neuter
 - newspaper-o
 - object-group
 - object-ungroup
 - odnoklassniki
 - odnoklassniki-square
 - opencart
 - openid
 - opera
 - optin-monster
 - outdent
 - pagelines
 - paint-brush
 - paper-plane
 - paper-plane-o
 - paperclip
 - paragraph
 - pause
 - pause-circle
 - pause-circle-o
 - paw
 - paypal
 - pencil
 - pencil-square
 - pencil-square-o
 - percent
 - phone
 - phone-square
 - picture-o
 - pie-chart
 - pied-piper
 - pied-piper-alt
 - pied-piper-pp
 - pinterest
 - pinterest-p
 - pinterest-square
 - plane
 - play
 - play-circle
 - play-circle-o
 - plug
 - plus
 - plus-circle
 - plus-square
 - plus-square-o
 - power-off
 - print
 - product-hunt
 - puzzle-piece
 - qq
 - qrcode
 - question
 - question-circle
 - question-circle-o
 - quote-left
 - quote-right
 - random
 - rebel
 - recycle
 - reddit
 - reddit-alien
 - reddit-square
 - refresh
 - registered
 - renren
 - repeat
 - reply
 - reply-all
 - retweet
 - road
 - rocket
 - rss
 - rss-square
 - rub
 - safari
 - scissors
 - scribd
 - search
 - search-minus
 - search-plus
 - sellsy
 - server
 - share
 - share-alt
 - share-alt-square
 - share-square
 - share-square-o
 - shield
 - ship
 - shirtsinbulk
 - shopping-bag
 - shopping-basket
 - shopping-cart
 - sign-in
 - sign-language
 - sign-out
 - signal
 - simplybuilt
 - sitemap
 - skyatlas
 - skype
 - slack
 - sliders
 - slideshare
 - smile-o
 - snapchat
 - snapchat-ghost
 - snapchat-square
 - sort
 - sort-alpha-asc
 - sort-alpha-desc
 - sort-amount-asc
 - sort-amount-desc
 - sort-asc
 - sort-desc
 - sort-numeric-asc
 - sort-numeric-desc
 - soundcloud
 - space-shuttle
 - spinner
 - spoon
 - spotify
 - square
 - square-o
 - stack-exchange
 - stack-overflow
 - star
 - star-half
 - star-half-o
 - star-o
 - steam
 - steam-square
 - step-backward
 - step-forward
 - stethoscope
 - sticky-note
 - sticky-note-o
 - stop
 - stop-circle
 - stop-circle-o
 - street-view
 - strikethrough
 - stumbleupon
 - stumbleupon-circle
 - subscript
 - subway
 - suitcase
 - sun-o
 - superscript
 - table
 - tablet
 - tachometer
 - tag
 - tags
 - tasks
 - taxi
 - television
 - tencent-weibo
 - terminal
 - text-height
 - text-width
 - th
 - th-large
 - th-list
 - themeisle
 - thumb-tack
 - thumbs-down
 - thumbs-o-down
 - thumbs-o-up
 - thumbs-up
 - ticket
 - times
 - times-circle
 - times-circle-o
 - tint
 - toggle-off
 - toggle-on
 - trademark
 - train
 - transgender
 - transgender-alt
 - trash
 - trash-o
 - tree
 - trello
 - tripadvisor
 - trophy
 - truck
 - try
 - tty
 - tumblr
 - tumblr-square
 - twitch
 - twitter
 - twitter-square
 - umbrella
 - underline
 - undo
 - universal-access
 - university
 - unlock
 - unlock-alt
 - upload
 - usb
 - usd
 - user
 - user-md
 - user-plus
 - user-secret
 - user-times
 - users
 - venus
 - venus-double
 - venus-mars
 - viacoin
 - viadeo
 - viadeo-square
 - video-camera
 - vimeo
 - vimeo-square
 - vine
 - vk
 - volume-control-phone
 - volume-down
 - volume-off
 - volume-up
 - weibo
 - weixin
 - whatsapp
 - wheelchair
 - wheelchair-alt
 - wifi
 - wikipedia-w
 - windows
 - wordpress
 - wpbeginner
 - wpforms
 - wrench
 - xing
 - xing-square
 - y-combinator
 - yahoo
 - yelp
 - yoast
 - youtube
 - youtube-play
 - youtube-square

(all-the-icons-insert-icons-for 'fileicon)
ꗪ - 1c
 - 1c-alt
 - MJML
 - R
 - abap
 - abif
 - access
 - actionscript
 - ada
 - ae
 - ai
 - akka
⧋ - alex
 - alloy
 - alpine-linux
 - ampl
 - amx
 - angelscript
Ⓐ - ansible
a - ansible-alt
 - ant
 - antlr
░ - antwar
 - api-blueprint
⍋ - apl
 - apl-old
 - apple
 - appveyor
 - arc
A - arch-linux
 - arduino
ⓐ - arttext
 - asciidoc
 - assembly
 - ats
 - audacity
 - augeas
 - aurelia
 - auto-hotkey
 - autoit
 - babel
 - bazel
 - bem
 - bib
 - bintray
 - bithound
 - blender
 - bluespec
 - boo
 - brain
 - brakeman
 - bro
 - broccoli
 - brotli
 - browserslist
 - brunch
 - buck
 - build-boot
 - bundler
 - byond
 - cabal
 - caddy
 - cake
 - cakefile
 - cakephp
 - cakephp-old
 - cc
 - ceylon
c - chai
 - chapel
 - chartjs
 - chef
 - chuck
 - circle-ci
 - cirru
 - ckeditor
 - clarion
 - clean
 - click
 - clips
 - clj
 - cljs
 - closure-template
 - cmake
 - cobol
☂ - codecov
 - codekit
 - codemirror
 - codeship
 - cold-fusion
 - clisp
 - composer
 - config
 - config-coffeescript
 - config-go
 - config-haskell
 - config-js
 - config-perl
 - config-python
 - config-react
 - config-ruby
 - config-rust
 - config-typescript
 - coq
 - cordova
 - cp
 - cpan
 - creole
 - crystal
 - cs-script
 - csound
 - cucumber
 - cython
 - d3
 - darcs
 - dart
 - dashboard
 - dbase
🗌 - default
 - delphi
 - devicetree
 - diff
 - dockerfile
 - doclets
 - doge
 - dom
🏁 - donejs
 - doxygen
👌 - dragula
 - drone
 - dyalog
 - dylib
E - e
 - eagle
 - easybuild
 - ec
 - ecere
 - edge
 - editorconfig
 - eiffel
 - ejs
 - electron
 - elm
 - emacs
 - elisp
 - ember
 - emberscript
 - eq
 - esdoc
 - eslint
 - eslint-old
 - excel
 - fabfile
 - factor
 - fancy
 - fantom
 - fbx
 - ffmpeg
 - finder
 - firebase
 - flow
 - flux
 - font
ﬀ - fontforge
 - fortran
 - franca
 - freemarker
 - frege
 - fsharp
 - fuel-ux
 - gams
 - gap
 - gdb
 - genshi
 - gentoo
 - gf
 - gitlab
 - glade
G - glyphs
 - gn
 - gnu
 - go
 - godot
 - golo
 - gosu
 - gradle
 - graphql
 - graphviz
 - groovy
 - grunt
 - gulp
 - hack
 - haml
 - harbour
 - hashicorp
 - haxe
 - haxedevelop
☿ - hg
 - hoplon
 - hy
 - icu
 - id
 - idl
 - idris
 - igorpro
 - image
 - inform7
 - inno
 - io
 - ioke
 - ionic-project
 - isabelle
 - j
 - jade
 - jake
 - jasmine
 - jenkins
 - jest
 - jinja
 - jison
 - jolie
 - jsonld
 - jsx
 - jsx-2
 - jsx2-alt
⛬ - julia
 - junos
 - jupyter
 - karma
 - keynote
 - khronos
 - kicad
 - kitchenci
 - kivy
K - knockout
 - kotlin
 - krl
 - labview
 - lasso
 - leaflet
L - lean
 - lerna
 - lfe
 - libuv
 - lightwave
 - lime
 - lisp
 - livescript
 - llvm
 - logtalk
 - lookml
 - lsl
 - lua
 - mako
 - man-page
 - mapbox
 - markdownlint
 - marko
 - mathematica
 - mathjax
 - matlab
 - max
 - maxscript
 - maya
 - mediawiki
 - mercury
 - meson
M - metal
 - meteor
 - microsoft-infopath
 - minecraft
 - minizinc
 - mirah
 - miranda
⛾ - mocha
 - modula-2
🕘 - moment
🌍 - moment-tz
 - monkey
 - moustache
 - mruby
 - mupad
 - nano
 - nanoc
 - nant
 - nasm
 - neko
 - netlogo
 - new-relic
󱑫 - nginx
✒ - nib
 - nimrod
 - nit
 - nix
 - nmap
 - nodemon
 - normalize
 - npm
 - npm-old
 - nsis
 - nsis-old
 - nuclide
 - nuget
 - numpy
 - nunjucks
 - nvidia
 - nxc
 - obj
 - objective-j
 - ocaml
 - octave
b36 - odin
 - onenote
 - ooc
☁ - opa
 - opencl
 - opengl
 - openoffice
 - openscad
 - org
 - owl
 - ox
 - oxygene
 - oz
 - p4
 - pan
 - papyrus
 - parrot
 - pascal
 - patch
♟ - pawn
 - pb
 - pegjs
 - raku
 - phalcon
 - phoenix
 - php
 - phpunit
 - pickle
 - pike
 - platformio
☰ - pm2
 - pod
 - pogo
 - pointwise
 - polymer
 - pony
 - postcss
 - postscript
P - povray
 - powerpoint
 - powershell
⊕ - precision
 - premiere
 - processing
 - progress
 - propeller
 - proselint
 - protractor
 - ps
 - pug
 - pug-alt
 - puppet
Ƶ - purebasic
 - purescript
 - racket
 - raml
 - rascal
 - rdoc
 - realbasic
 - reason
 - rebol
 - red
 - redux
* - regex
 - rexx
 - rhino
💍 - ring
 - riot
 - robot
 - rollup
 - rollup-old
🝤 - rot
 - rspec
 - rst
 - sage
 - saltstack
 - sas
 - sbt
 - sc
λ - scheme
 - scilab
 - scrutinizer
 - self
 - sequelize
 - sf
 - shen
⛵ - shipit
 - shippable
 - shopify
✫ - shuriken
 - silverstripe
 - sinatra
 - sketch
 - sketchup-layout
 - sketchup-make
 - sketchup-stylebuilder
 - slash
 - snyk
 - solidity
 - sparql
 - spray
 - sqf
 - sqlite
 - squarespace
 - stan
 - stata
 - storyist
 - strings
 - stylelint
s - stylus
 - stylus-full
S - stylus-orb
 - sublime
 - sv
㏜ - svelte
 - svn
 - swagger
 - tag
 - tcl
✈ - telegram
 - terminal
🕊 - tern
 - terraform
 - test-coffeescript
 - test-dir
 - test-generic
 - test-js
 - test-perl
 - test-python
 - test-react
 - test-ruby
 - test-typescript
 - tex
t - textile
™ - textmate
 - thor
 - tinymce
 - tsx
 - tsx-alt
T - tt
 - turing
⸙ - twig
 - twine
 - txl
 - typedoc
 - typescript
ʦ - typescript-alt
 - typings
 - uno
u - unreal
 - urweb
 - v8
V - vagrant
 - vcl
 - verilog
 - vertex-shader
 - vhdl
 - video
 - virtualbox
 - virtualbox-alt
 - visio
 - vmware
 - vue
 - wasm
 - watchman
 - webgl
 - webpack
 - webpack-old
 - wercker
 - word
Ⅹ - x10
 - xamarin
X - xmos
 - xpages
 - xtend
 - yarn
 - yasm
☯ - yin-yang
 - yoyo
 - yui
 - zbrush
 - zephir
z - zig
 - zimpl



(provide 'all-the-icons)
;;; all-the-icons.el ends here
