(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ace-window-display-mode t)
 '(blacken-line-length 79)
 '(column-number-mode t)
 '(command-log-mode-is-global t)
 '(company-show-quick-access t)
 '(company-tooltip-align-annotations t)
 '(custom-safe-themes
   '("abd2ad651d2d0feb3aa165536cff555308d17068bc9c73f020a9e7faadf0720b" "a687c49ab637fb934e2676c782a891de0f2f0a0599e34b18471fcab9d27c1119" "b9e9ba5aeedcc5ba8be99f1cc9301f6679912910ff92fdf7980929c2fc83ab4d" "1084e940e1529866da525e07800656de811e23a569962506ffb00f007699386d" "05bf0101e1cc26c47c94fffc7275886a12c2b7fd5b47286672897e9f5ddcc4b2" "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" default))
 '(debug-on-error nil)
 '(delimit-columns-before "")
 '(desktop-save-mode nil)
 '(display-fill-column-indicator t)
 '(display-fill-column-indicator-column t)
 '(display-line-numbers-type 'relative)
 '(doom-modeline-highlight-modified-buffer-name t)
 '(doom-modeline-mode t)
 '(elpy-eldoc-show-current-function nil)
 '(elpy-rpc-ignored-buffer-size 204800)
 '(fill-column 79)
 '(flycheck-flake8-maximum-line-length 79)
 '(flycheck-mode-line-prefix "  ")
 '(flycheck-yamllintrc (concat (getenv "HOME") "/.config/yamllint/config"))
 '(git-gutter:added-sign "▎")
 '(git-gutter:deleted-sign "▎")
 '(git-gutter:modified-sign "▎")
 '(global-auto-revert-mode t)
 '(global-display-fill-column-indicator-mode t)
 '(global-display-line-numbers-mode t)
 '(global-flycheck-mode t)
 '(global-git-gutter-mode t)
 '(global-hl-line-mode t)
 '(global-tab-line-mode t)
 '(global-whitespace-mode nil)
 '(grep-command "grep --color=auto -nH --null -e ")
 '(grep-find-command
   '("find . -type f -exec grep --color=auto -nH --null -e  \\{\\} +" . 54))
 '(helm-minibuffer-history-mode t)
 '(helm-mode t)
 '(highlight-indentation-blank-lines t)
 '(ignored-local-variable-values
   '((vc-prepare-patches-separately)
     (diff-add-log-use-relative-names . t)
     (vc-git-annotate-switches . "-w")))
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(kill-whole-line t)
 '(lsp-completion-show-detail nil)
 '(lsp-file-watch-threshold 3000)
 '(lsp-java-autobuild-enabled nil)
 '(lsp-java-code-generation-generate-comments t)
 '(lsp-java-code-generation-hash-code-equals-use-instanceof t)
 '(lsp-java-code-generation-to-string-code-style "STRING_FORMAT")
 '(lsp-java-completion-import-order ["java" "javax" "org" "com" "se"])
 '(lsp-java-completion-max-results 10)
 '(lsp-java-configuration-maven-user-settings (concat (getenv "HOME") "/.m2/settings.xml"))
 '(lsp-java-configuration-runtimes [])
 '(lsp-java-configuration-update-build-configuration "interactive")
 '(lsp-java-content-provider-preferred nil)
 '(lsp-java-dependency-package-representation "hierarchical")
 '(lsp-java-format-settings-profile "JCAT code formatter")
 '(lsp-java-format-settings-url
   (concat emx/USER_REPO_ROOT "/dj/jcat-common-code-formatter/src/main/resources/jcat-code-formatter.xml"))
 '(lsp-java-import-gradle-enabled nil)
 '(lsp-java-import-gradle-jvm-arguments [])
 '(lsp-java-import-gradle-wrapper-enabled nil)
 '(lsp-java-java-path "/app/vbuild/SLED12-x86_64/openjdk/latest/bin/java")
 '(lsp-java-jdt-download-url
   (concat "file://" emx/USER_REPO_ROOT "/ws/bin/jdt-language-server-1.19.0-202301090450.tar.gz"))
 '(lsp-java-maven-download-sources t)
 '(lsp-java-max-concurrent-builds 2)
 '(lsp-java-save-actions-organize-imports t)
 '(lsp-java-server-launch-mode "LightWeight")
 '(lsp-java-theme "vscode")
 '(lsp-java-vmargs
   '("-XX:+UseParallelGC" "-XX:GCTimeRatio=4" "-XX:AdaptiveSizePolicyWeight=90" "-Dsun.zip.disableMemoryMapping=true" "-Xmx4G" "-Xms100m"))
 '(lsp-keep-workspace-alive nil)
 '(lsp-keymap-prefix "C-c l")
 '(lsp-lens-enable nil)
 '(lsp-log-max 100)
 '(lsp-metals-ammonite-jvm-properties [])
 '(lsp-metals-bloop-sbt-already-installed t)
 '(lsp-metals-coursier-download-url
   (concat "file://" emx/USER_REPO_ROOT "/ws/bin/cs-x86_64-pc-linux-v2.1.0-RC6.gz"))
 '(lsp-metals-enable-indent-on-paste t)
 '(lsp-metals-java-home "/app/vbuild/SLED12-x86_64/openjdk/latest")
 '(lsp-metals-sbt-script "/app/vbuild/RHEL7-x86_64/sbt/1.8.2/bin/sbt")
 '(lsp-metals-server-args '("-J-Dmetals.allow-multiline-string-formatting=off"))
 '(lsp-metals-treeview-logging t)
 '(lsp-pylsp-plugins-autopep8-enabled t)
 '(lsp-treemacs-sync-mode t)
 '(magit-auto-revert-mode t)
 '(magit-blame-styles
   '((headings
      (heading-format . "%-20a %C %s(%H)
"))
     (highlight
      (highlight-face . magit-blame-highlight))
     (lines
      (show-lines . t)
      (show-message . t))))
 '(max-lisp-eval-depth 100000)
 '(max-specpdl-size 4)
 '(menu-bar-mode nil)
 '(mode-line-compact 'long)
 '(neo-smart-open t)
 '(neo-vc-integration '(face char))
 '(nxml-child-indent 4)
 '(plantuml-default-exec-mode 'jar)
 '(plantuml-indent-level 4)
 '(plantuml-jar-path
   "/app/vbuild/tools/plantuml/1.2022.5/lib/plantuml.1.2022.5.jar")
 '(ring-bell-function 'ignore)
 '(rust-format-on-save t)
 '(scala-indent:step 4)
 '(scroll-bar-mode nil)
 '(send-mail-function 'mailclient-send-it)
 '(show-paren-mode t)
 '(show-trailing-whitespace t)
 '(size-indication-mode t)
 '(sml/full-mode-string "  ")
 '(sml/mode-width 'right)
 '(sml/modified-char "  ")
 '(sml/name-width 50)
 '(sml/not-modified-char "  ")
 '(sml/outside-modified-char "  ")
 '(sml/pre-id-separator " ")
 '(sml/pre-modes-separator " ")
 '(sml/prefix-face-list
   '((":SU:" sml/sudo)
     ("" sml/git)
     (sml/projectile-replacement-format sml/projectile)
     ("" sml/prefix)))
 '(sml/read-only-char "  ")
 '(sml/replacer-regexp-list
   '(("^~/org/" ":Org:")
     ("^~/\\.emacs\\.d/elpa/" ":ELPA:")
     ("^~/\\.emacs\\.d/" ":ED:")
     ("^/sudo:.*:" ":SU:")
     ("^~/Documents/" ":Doc:")
     ("^~/Dropbox/" ":DB:")
     ("^:\\([^:]*\\):Documento?s/" ":\\1/Doc:")
     ("^~/[Gg]it/" ":Git:")
     ("^~/[Gg]it[Hh]ub/" ":Git:")
     ("^~/[Gg]it\\([Hh]ub\\|\\)-?[Pp]rojects/" ":Git:")))
 '(sml/shorten-directory t)
 '(sml/shorten-mode-string "  ")
 '(sml/shorten-modes nil)
 '(sml/show-remote nil)
 '(sml/vc-mode-show-backend t)
 '(tab-bar-close-button-show nil)
 '(tab-bar-format
   '(tab-bar-format-history tab-bar-format-tabs tab-bar-separator tab-bar-format-align-right))
 '(tab-bar-history-mode t)
 '(tab-bar-mode t)
 '(tab-bar-new-tab-choice "~/.emacs.d/init.el")
 '(tab-bar-select-tab-modifiers '(meta))
 '(tab-bar-show 1)
 '(tab-bar-tab-hints t)
 '(tab-line-close-button-show nil)
 '(tab-line-new-button-show nil)
 '(tab-line-switch-cycling t)
 '(tab-line-tab-name-function 'tab-line-tab-name-buffer)
 '(tab-width 4)
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(treemacs--fringe-indicator-bitmap 'treemacs--fringe-indicator-bitmap-default)
 '(treemacs-collapse-dirs 3)
 '(treemacs-filewatch-mode t)
 '(treemacs-follow-after-init t)
 '(treemacs-follow-mode t)
 '(treemacs-fringe-indicator-mode nil)
 '(treemacs-git-mode t)
 '(treemacs-project-follow-cleanup t)
 '(treemacs-recenter-after-file-follow 'on-distance)
 '(treemacs-recenter-after-tag-follow 'on-distance)
 '(treemacs-select-when-already-in-treemacs 'next-or-back)
 '(treemacs-workspace-switch-cleanup 'all)
 '(undo-no-redo t)
 '(warning-minimum-level :emergency)
 '(yas-global-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#231f32" :foreground "#b7b7ff" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 180 :width normal :foundry "outline" :family "Hack Nerd Font"))))
 '(Man-overstrike ((t (:inherit font-lock-type-face :weight bold))))
 '(Man-underline ((t (:inherit font-lock-keyword-face :underline t))))
 '(company-template-field ((t (:background "#b7b7ff" :foreground "#181522"))))
 '(company-tooltip ((t (:background "#30304e"))))
 '(company-tooltip-annotation ((t (:foreground "#e3cfcf"))))
 '(company-tooltip-annotation-selection ((t (:inherit company-tooltip-annotation :foreground "#c2f0c2"))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-common :foreground "#ff9d9d"))))
 '(company-tooltip-selection ((t (:extend t :background "#181522"))))
 '(custom-button ((t (:background "slate gray" :foreground "black"))))
 '(custom-button-mouse ((t (:background "slate gray" :foreground "black"))))
 '(custom-button-pressed ((t (:background "slate gray" :foreground "black"))))
 '(custom-comment ((t (:background "#181522" :foreground "#d1ccba"))))
 '(doom-modeline-project-dir ((t (:inherit (w-mode-line-head bold)))))
 '(error ((t (:foreground "tomato" :weight bold))))
 '(fill-column-indicator ((t (:inherit font-lock-comment-face))))
 '(git-gutter:deleted ((t (:inherit default :foreground "#e80000" :weight bold))))
 '(header-line ((t (:background "#8585ff" :foreground "#231f32" :inverse-video t :box (:line-width (1 . -1) :color "red" :style released-button)))))
 '(helm-buffer-directory ((t (:inherit font-lock-doc-face))))
 '(helm-ff-directory ((t (:inherit font-lock-doc-face))))
 '(helm-ff-dotted-directory ((t (:extend t :foreground "turquoise"))))
 '(helm-ff-file-extension ((t (:inherit font-lock-type-face))))
 '(helm-selection ((t (:inherit hl-line))))
 '(helm-source-header ((t (:extend t :background "#181522" :foreground "#b7b7ff" :weight bold :height 1.3))))
 '(highlight-indentation-current-column-face ((t (:background "#181522"))))
 '(highlight-indentation-face ((t (:background "#2e2942"))))
 '(hl-line ((t (:extend t :background "#30304e"))))
 '(info-menu-star ((t (:foreground "#d87373"))))
 '(info-node ((t (:foreground "#ffb733" :slant italic :weight bold))))
 '(info-title-1 ((t (:foreground "#938760" :weight bold))))
 '(info-title-2 ((t (:foreground "#bdb59b" :weight bold))))
 '(info-title-3 ((t (:foreground "#bdb59b" :weight bold))))
 '(info-title-4 ((t (:foreground "#e3cfcf" :weight bold))))
 '(isearch ((t (:background "lightslateblue" :foreground "black"))))
 '(isearch-group-1 ((t (:background "gainsboro" :foreground "black"))))
 '(isearch-group-2 ((t (:background "bisque" :foreground "black"))))
 '(line-number-current-line ((t (:inherit line-number :background "#231f32" :foreground "#ffb733"))))
 '(link ((t (:foreground "lightslateblue" :underline t))))
 '(link-visited ((t (:inherit link :foreground "orchid"))))
 '(lsp-headerline-breadcrumb-path-face ((t (:background "#8585ff" :foreground "#231f32"))))
 '(lsp-headerline-breadcrumb-separator-face ((t (:background "#8585ff" :foreground "#231f32" :height 0.8))))
 '(lsp-headerline-breadcrumb-symbols-face ((t (:inherit font-lock-doc-face :background "#8055cc" :foreground "#231f32" :weight bold))))
 '(magit-blame-hash ((t (:foreground "#656500"))))
 '(magit-blame-highlight ((t (:extend t :foreground "#2a662a"))))
 '(magit-section-highlight ((t (:extend t :background "gray18"))))
 '(markdown-highlighting-face ((t (:background "salmon" :foreground "linen"))))
 '(match ((t (:background "#8584ff" :foreground "#00006b"))))
 '(minibuffer-prompt ((t (:background "#30304e" :foreground "lavender" :box (:line-width (1 . -1) :color "red" :style released-button) :weight bold))))
 '(mode-line ((t (:background "#181522" :foreground "#62629c" :family "Hack Nerd Font"))))
 '(mode-line-inactive ((t (:inherit mode-line :background "#545454" :foreground "#a8a8a8" :weight light))))
 '(neo-file-link-face ((t (:inherit header-line))))
 '(neo-vc-conflict-face ((t (:foreground "#844a4a"))))
 '(neo-vc-default-face ((t (:foreground "#62629c"))))
 '(neo-vc-edited-face ((t (:foreground "#cc8400"))))
 '(neo-vc-unlocked-changes-face ((t (:foreground "#ff9d9d"))))
 '(neo-vc-up-to-date-face ((t (:foreground "#62629c"))))
 '(neo-vc-user-face ((t (:foreground "#e80000" :slant italic))))
 '(org-block ((t (:inherit shadow :extend t :background "#181522"))))
 '(org-block-begin-line ((t (:inherit org-meta-line :extend t :background "#181522"))))
 '(org-code ((t (:inherit shadow :background "#181522"))))
 '(rainbow-delimiters-base-face ((t (:inherit default))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "#a8a8a8"))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit rainbow-delimiters-base-face :foreground "#ffe4b3"))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#d1c0ba"))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit rainbow-delimiters-base-face :foreground "#ffffb7"))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#e3cfcf"))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit rainbow-delimiters-base-face :foreground "#c2f0c2"))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#ffd3d3"))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit rainbow-delimiters-base-face :foreground "#8585ff"))))
 '(rainbow-delimiters-depth-9-face ((t (:inherit rainbow-delimiters-base-face :foreground "#b7ffff"))))
 '(sml/col-number ((t (:foreground "moccasin"))))
 '(sml/filename ((t (:inherit sml/global :foreground "#a8ff51" :weight bold))))
 '(sml/git ((t (:foreground "#84b384"))))
 '(sml/line-number ((t (:foreground "moccasin" :inverse-video nil))))
 '(sml/modes ((t (:inherit sml/prefix :foreground "#8585ff"))))
 '(sml/modified ((t (:inherit sml/not-modified :foreground "#d87373" :weight bold))))
 '(sml/not-modified ((t (:foreground "#a8ff51"))))
 '(sml/outside-modified ((t (:inherit sml/not-modified :foreground "#820000"))))
 '(sml/prefix ((t (:inherit sml/global :foreground "#8585ff"))))
 '(sml/sudo ((t (:foreground "#7141c6"))))
 '(tab-bar ((t (:inherit variable-pitch :background "#080808" :foreground "#8584ff" :family "Hack Nerd Font"))))
 '(tab-bar-tab-group-current ((t (:foreground "#8584ff" :box nil :weight bold))))
 '(tab-bar-tab-group-inactive ((t (:foreground "#303030"))))
 '(tab-bar-tab-inactive ((t (:inherit tab-bar-tab :foreground "#303030"))))
 '(tab-bar-tab-ungrouped ((t (:background "#303030" :foreground "#62629c"))))
 '(tab-line ((t (:inherit variable-pitch :background "#181522" :foreground "#62629c" :height 0.9 :family "Hack Nerd Font"))))
 '(tab-line-highlight ((t (:background "#820000" :foreground "#ffff9d" :box (:line-width (1 . 1) :style released-button)))))
 '(tab-line-tab ((t (:inherit tab-line))))
 '(tab-line-tab-current ((t (:inherit mode-line-buffer-id))))
 '(tab-line-tab-inactive ((t (:inherit tab-line-tab :foreground "#62629c"))))
 '(tab-line-tab-modified ((t (:inherit w-mode-line-head-modified))))
 '(treemacs-git-commit-diff-face ((t (:inherit 'warning))))
 '(vc-state-base ((t (:foreground "slategray"))))
 '(vertical-border ((t (:background "#231f32" :foreground "#74564c"))))
 '(w-mode-line-head ((t (:foreground "#8181b0"))))
 '(w-mode-line-head-modified ((t (:foreground "#d87373"))))
 '(w-mode-line-tail ((t (:foreground "#8181b0"))))
 '(w-mode-line-tail-modified ((t (:foreground "#d87373"))))
 '(warning ((t (:foreground "gold" :weight bold))))
 '(widget-field ((t (:extend t :background "#b7b7ff" :foreground "#181522"))))
 '(woman-bold ((t (:inherit font-lock-type-face))))
 '(woman-italic ((t (:inherit font-lock-keyword-face)))))
